name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          REACT_APP_API_KEY: '${{ secrets.REACT_APP_API_KEY }}'
          REACT_APP_AUTH_DOMAIN: '${{ secrets.REACT_APP_AUTH_DOMAIN }}'
          REACT_APP_DATA_BASE_URL: '${{ secrets.REACT_APP_DATA_BASE_URL }}'
          REACT_APP_PROJECT_ID: '${{ secrets.REACT_APP_PROJECT_ID }}'
          REACT_APP_STORAGE_BUCKET: '${{ secrets.REACT_APP_STORAGE_BUCKET }}'
          REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}'
          REACT_APP_ID: '${{ secrets.REACT_APP_ID }}'
          REACT_APP_MEASUREMENT_ID: '${{ secrets.REACT_APP_MEASUREMENT_ID }}'