name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: NodeJs-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Issue Description'
        pr-message: 'How the error happen'
